is_run_all = false
is_run_asm = false
is_run_pcga = false
is_run_esmda = true
is_run_sies = false
is_parallel = false
max_workers = 2
language = "english"
n_pc = 5
n_fields_es = 10
esmda_variant = "base"
esmda_localization_strategy = "base"
is_gray_scale = true
duration_in_days = 30
duration_in_days_inv = 30
is_run_pcga_old = false
is_export_animations= false
is_use_exact_std = true
